### PR TITLE
Card, Deck, Topic POJOs

### LINKED ISSUE #1: Topic POJO
<ul>
<li>One to many Decks</li>
<li>String title</li>
</ul>

### LINKED ISSUE #2: Deck POJO
<ul>
<li>One to many Cards</li>
<li>String title</li>
</ul>

### LINKED ISSUE #3: Card POJO
<ul>
<li>Many to one Deck</li>
<li>String phrase (front)</li>
<li>String description (back)</li>
</ul>

### PR DESCRIPTION
**Pull request by ColinWake**
Card POJO containing term and definition, Deck POJO containing title and Cards, Topic POJO containing title and Decks.
All relationships are mapped

Closes #1 
Closes #2 
Closes #3

### CODE REVIEW

**Review by ndought — APPROVED** [review]
Looks good

**Review by caleb-bb — APPROVED** [review]

**Review by JHardeman — COMMENTED** [review]
Sweet

**Comment by NightingaleMedia** [comment]
approve

**Review by NightingaleMedia — COMMENTED** [review]
looks good

**Pull request merged**
